### ISSUE TITLE
Node-Red support for m2 version

### ISSUE THREAD

**Issue by wojtulab** [aformusatii/node-red-contrib-xiaomi-miio#3]
Hello,
I've installed :  
```
npm install node-red-contrib-xiaomi-miio
npm install -g miio
```

In the nodered I am trying to execute any commands with failure:

for example
```
msg = {
    payload: {
        power: true
    
    }
}
return msg;
```

![image](https://user-images.githubusercontent.com/14801148/37204530-68bbac5e-2391-11e8-90af-48c2248bef02.png)

`msg : error
"TypeError: device.setPower is not a function"`

Getting the status via node-red
![image](https://user-images.githubusercontent.com/14801148/37204882-ddab016c-2392-11e8-8d8e-c80c91fccf34.png)

but the NPM can successfully detect, query or control all properties usuing miio library:
_miio inspect 70545715_
```
Properties:
  - power: false
  - mode: idle
  - temperature: 20.6
  - humidity: 60
  - aqi: 49
  - favoriteLevel: 10
  - filterLifeRemaining: 99
  - filterHoursUsed: 15
  - useTime: 55200
  - led: true
  - ledBrightness: bright
  - buzzer: true

```
_miio control 70545715 power true_
```
INFO  Attempting to invoke power on 70545715
true
```
and again query the parameters:
_miio inspect 70545715_
```
Properties:
  **- power: true**
  - mode: idle
```
Please find that my AirPurifier is a zhimi.airpurifier.**m2**
